#!/usr/bin/env bash
# Superset workspace setup — runs once, when Superset creates the worktree.
#
# Wired via .superset/config.json ("setup"). Superset runs it in a terminal in
# the new worktree with SUPERSET_ROOT_PATH / SUPERSET_WORKSPACE_NAME /
# SUPERSET_WORKSPACE_PATH exported. A non-zero exit surfaces as an error toast.
#
# Makes a fresh worktree runnable: Python env, UI deps, browsers, and the
# per-workspace port assignment that .superset/run.sh will use.
#
# Knobs (export before workspace creation, or set in .superset/config.local.json):
#   HAL0_SETUP_SKIP_PLAYWRIGHT=1  skip the chromium download
#   HAL0_SETUP_SKIP_UI=1          skip npm ci entirely (backend-only work)

set -euo pipefail

if [[ -t 1 ]]; then
    GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
    BOLD='\033[1m'; RESET='\033[0m'; DIM='\033[2m'
else
    GREEN=''; YELLOW=''; RED=''; BOLD=''; RESET=''; DIM=''
fi

info() { printf "${GREEN}✔${RESET}  %s\n" "$*"; }
warn() { printf "${YELLOW}!${RESET}  %s\n" "$*" >&2; }
step() { printf "\n${BOLD}── %s${RESET}\n" "$*"; }
die()  { printf "${RED}✗${RESET}  %s\n" "$*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=ports.sh
source "${SCRIPT_DIR}/ports.sh"
cd "${HAL0_WORKSPACE_PATH}"

step "Workspace"
printf '  path     %s\n' "${HAL0_WORKSPACE_PATH}"
printf '  name     %s\n' "${HAL0_WORKSPACE_NAME}"
printf '  branch   %s\n' "$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '(detached)')"
printf '  ports    api %s · ui %s · openwebui %s\n' \
    "${HAL0_PORT}" "${UI_PORT}" "${HAL0_OPENWEBUI_PORT}"

# ── Python ───────────────────────────────────────────────────────────────────
step "Python environment"

if command -v uv >/dev/null 2>&1; then
    # Same install path as CI (CONTRIBUTING §10: "pin the environment") so a
    # workspace can't skew from the lockfile CI resolves against.
    uv sync --frozen --extra dev
    info "uv sync --frozen --extra dev"
elif command -v python3 >/dev/null 2>&1; then
    warn "uv not found — falling back to venv + pip (may drift from uv.lock)"
    [[ -d .venv ]] || python3 -m venv .venv
    ./.venv/bin/python -m pip install --quiet --upgrade pip
    ./.venv/bin/python -m pip install --quiet -e ".[dev]"
    info "pip install -e .[dev]"
else
    die "neither uv nor python3 found — cannot build a Python environment"
fi

# ── UI ───────────────────────────────────────────────────────────────────────
if [[ "${HAL0_SETUP_SKIP_UI:-0}" == "1" ]]; then
    step "UI dependencies"
    warn "HAL0_SETUP_SKIP_UI=1 — skipping npm and Playwright"
elif ! command -v npm >/dev/null 2>&1; then
    step "UI dependencies"
    warn "npm not found — skipping UI deps. \`make ui-dev\` and the e2e suite will not run."
else
    step "UI dependencies"
    if [[ -f ui/package-lock.json ]]; then
        ( cd ui && npm ci --no-audit --fund=false )
        info "npm ci"
    else
        ( cd ui && npm install --no-audit --fund=false )
        warn "no ui/package-lock.json — used npm install"
    fi

    if [[ "${HAL0_SETUP_SKIP_PLAYWRIGHT:-0}" == "1" ]]; then
        warn "HAL0_SETUP_SKIP_PLAYWRIGHT=1 — skipping browser download"
    else
        # No --with-deps: that needs sudo and would block setup on a password
        # prompt inside Superset's terminal. The browser cache is global
        # (~/.cache/ms-playwright), so this is a no-op after the first
        # workspace. If e2e later complains about missing system libraries,
        # run `npm run test:e2e:install` once, by hand, with sudo available.
        ( cd ui && npx --no-install playwright install chromium ) \
            || warn "playwright install failed — run 'npm run test:e2e:install' by hand"
        info "Playwright chromium ready"
    fi
fi

# ── Local env carry-over ─────────────────────────────────────────────────────
step "Local environment"

# Superset's documented pattern: seed the worktree from the primary checkout's
# untracked local config. Never clobber a file the workspace already has.
if [[ -n "${SUPERSET_ROOT_PATH:-}" && -f "${SUPERSET_ROOT_PATH}/ui/.env" && ! -f ui/.env ]]; then
    cp "${SUPERSET_ROOT_PATH}/ui/.env" ui/.env
    info "copied ui/.env from ${SUPERSET_ROOT_PATH}"
fi

# Port assignment, written where a human (or a hand-run command) can source it.
# Gitignored — it is per-workspace, machine-local state.
cat > "${SCRIPT_DIR}/workspace.env" <<EOF
# Generated by .superset/setup.sh — per-workspace, gitignored, safe to delete.
# Re-derive at any time with: source .superset/ports.sh
export HAL0_WORKSPACE_NAME="${HAL0_WORKSPACE_NAME}"
export HAL0_HOME="${HAL0_HOME}"
export HAL0_PORT="${HAL0_PORT}"
export UI_PORT="${UI_PORT}"
export HAL0_OPENWEBUI_PORT="${HAL0_OPENWEBUI_PORT}"
export HAL0_OWU_CONTAINER="${HAL0_OWU_CONTAINER}"
export VITE_API_TARGET="${VITE_API_TARGET}"
EOF
info "wrote .superset/workspace.env"

step "Ready"
printf '  Run button   %sapi :%s · ui :%s%s\n' "${BOLD}" "${HAL0_PORT}" "${UI_PORT}" "${RESET}"
printf '  %sTests:  make test  ·  cd ui && npm run test:e2e%s\n' "${DIM}" "${RESET}"
printf '  %sShell:  source .superset/workspace.env%s\n\n' "${DIM}" "${RESET}"
