"""Route-sync check: every classified admin tool resolves to a live route.

Since spec §4.4 the ``_REST_MAP`` / ``_PATH_ARGS`` tables are AUTOGENERATED
from ``create_app().routes`` (route-id keyed) and re-keyed onto stable tool
names via the hand-authored ``TOOL_NAME_ALIASES`` overlay. This test pins the
autogen against the live app:

* every ``TOOL_NAME_ALIASES`` route_id is registered by the real app (the
  "classified but no live route" guard — the old drift class that caught the
  ``upstream_update`` PATCH route), and
* the reconstructed ``_PATH_ARGS`` mirror each route template's placeholders.

The conftest fixture installs the live map before each test, so ``admin``
here reflects ``create_app()``'s generated tables.
"""

from __future__ import annotations

import re

from hal0.api import create_app
from hal0.mcp import admin


def _live_route_ids() -> set[str]:
    """``"<METHOD>:<path-template>"`` ids the live app registers (normalized).

    Enumerates via ``admin._iter_leaf_routes`` rather than a private flat loop
    over ``app.routes``. A second, independent walk was a second owner of "how
    do you find a route", and it rotted the same way the first one did: under
    FastAPI 0.138 (``include_router`` leaves ``_IncludedRouter`` wrappers in
    ``app.routes``) this function returned an empty set and both assertions
    below failed with all ~85 classified routes reported missing — a false
    alarm about the catalog when the walk was what broke.
    """
    live: set[str] = set()
    for route in admin._iter_leaf_routes(create_app().routes):
        methods = getattr(route, "methods", None)
        path = getattr(route, "path", None)
        if not methods or not path:
            continue
        norm = admin._normalize_path(path)
        live |= {f"{method.upper()}:{norm}" for method in methods}
    return live


def test_every_classified_route_id_resolves_to_a_live_route() -> None:
    live = _live_route_ids()
    missing = sorted(rid for rid in admin.TOOL_NAME_ALIASES if rid not in live)
    assert not missing, f"classified route_ids with no live route: {missing}"


def test_rest_map_targets_resolve_to_live_routes() -> None:
    """The reconstructed tool -> (method, path) view still points at live routes."""
    live = _live_route_ids()
    missing = sorted(
        f"{tool}: {method} {template} not registered"
        for tool, (method, template) in admin._REST_MAP.items()
        if f"{method}:{template}" not in live
    )
    assert not missing, missing


def test_rest_map_path_placeholders_match_path_args() -> None:
    for tool, (_method, template) in admin._REST_MAP.items():
        placeholders = set(re.findall(r"{(\w+)}", template))
        declared = set(admin._PATH_ARGS.get(tool, ()))
        assert placeholders == declared, (
            f"{tool}: template placeholders {sorted(placeholders)} != _PATH_ARGS {sorted(declared)}"
        )
