"""Render ``/etc/hal0/honcho.env`` for the self-hosted Honcho v3 docker compose stack.

Honcho is an opt-in alternative memory provider (``[honcho]`` in hal0.toml,
selected per-agent via ``memory.agent_providers``). Its compose stack reads
its LLM routing entirely from environment variables (no TOML/YAML config of
its own), so hal0 owns a single generated env file the compose unit
``env_file:``-mounts.

Every Honcho LLM feature (deriver / dialectic / summary / dream / embedding)
can be pointed at the local hal0-api gateway (default, keyless) or a cloud
upstream via ``base_url`` + ``api_key_env``. The env var *name* is written
into the file; the corresponding secret *value* is expected to live in
``/var/lib/hal0/secrets/honcho.env``, which the operator maintains by hand
and this renderer appends verbatim so both files ship together to compose.

Privileged operation: writing under ``/etc/hal0`` + restarting a unit needs
root. Best-effort like :mod:`hal0.memory.extraction_env` — returns a status
dict rather than raising, so the API can surface a partial result instead of
500ing.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, Any

import structlog

if TYPE_CHECKING:
    from hal0.config.schema import Hal0Config, HonchoLLMFeatureConfig

log = structlog.get_logger(__name__)

#: Generated env file the hal0-honcho compose stack mounts via env_file:.
HONCHO_ENV_PATH = Path("/etc/hal0/honcho.env")

#: systemd unit fronting the Honcho docker compose stack.
HONCHO_SERVICE = "hal0-honcho"

#: Containers reach the host hal0-api gateway via the docker host-gateway alias.
LOCAL_BASE_URL = "http://host.docker.internal:8080/v1"

#: Honcho requires LLM_OPENAI_API_KEY non-empty even for a keyless local endpoint.
LOCAL_API_KEY = "hal0-local-noauth"

#: Per-feature model id used when the operator leaves `model` empty in hal0.toml.
DEFAULT_FEATURE_MODELS: dict[str, str] = {
    "deriver": "hal0/utility",
    "dialectic": "hal0/agent",
    "summary": "hal0/utility",
    "dream": "hal0/utility",
    "embedding": "qwen3-embedding-0-6b-q8-0",
}

#: Operator-maintained secrets (cloud API key values). Appended verbatim, not templated.
SECRETS_PATH = Path("/var/lib/hal0/secrets/honcho.env")

_DIALECTIC_LEVELS = ("minimal", "low", "medium", "high", "max")

_HEADER = (
    "# Generated by hal0 from /etc/hal0/hal0.toml [honcho]. Do not hand-edit —\n"
    "# changes are overwritten the next time the Honcho config is applied.\n"
)


def _resolve(feature: HonchoLLMFeatureConfig, feature_name: str) -> tuple[str, str]:
    """Return (model, base_url) for ``feature``, filling in local defaults."""
    model = feature.model or DEFAULT_FEATURE_MODELS[feature_name]
    base_url = feature.base_url or LOCAL_BASE_URL
    return model, base_url


def _emit_model_config(
    lines: list[str], prefix: str, feature: HonchoLLMFeatureConfig, feature_name: str
) -> None:
    model, base_url = _resolve(feature, feature_name)
    lines.append(f"{prefix}__TRANSPORT={feature.transport}")
    lines.append(f"{prefix}__MODEL={model}")
    lines.append(f"{prefix}__OVERRIDES__BASE_URL={base_url}")
    if feature.api_key_env:
        lines.append(f"{prefix}__OVERRIDES__API_KEY_ENV={feature.api_key_env}")


def render_env(cfg: Hal0Config) -> str:
    """Render the full ``honcho.env`` contents for ``cfg.honcho``.

    Deterministic given ``cfg`` — no filesystem reads except appending the
    operator secrets file verbatim (if present) at the very end.
    """
    honcho = cfg.honcho
    llm = honcho.llm

    lines: list[str] = [_HEADER.rstrip("\n")]
    lines.append(f"LLM_OPENAI_API_KEY={LOCAL_API_KEY}")

    if honcho.auth_enabled:
        lines.append("AUTH_USE_AUTH=true")
        lines.append("# AUTH_JWT_SECRET expected in the operator secrets file appended below.")
    else:
        lines.append("AUTH_USE_AUTH=false")

    lines.append("EMBED_MESSAGES=true")
    lines.append(f"EMBEDDING_VECTOR_DIMENSIONS={llm.embedding_dimensions}")
    _emit_model_config(lines, "EMBEDDING_MODEL_CONFIG", llm.embedding, "embedding")

    _emit_model_config(lines, "DERIVER_MODEL_CONFIG", llm.deriver, "deriver")
    _emit_model_config(lines, "SUMMARY_MODEL_CONFIG", llm.summary, "summary")

    _emit_model_config(lines, "DREAM_DEDUCTION_MODEL_CONFIG", llm.dream, "dream")
    _emit_model_config(lines, "DREAM_INDUCTION_MODEL_CONFIG", llm.dream, "dream")

    for level in _DIALECTIC_LEVELS:
        _emit_model_config(
            lines, f"DIALECTIC_LEVELS__{level}__MODEL_CONFIG", llm.dialectic, "dialectic"
        )

    rendered = "\n".join(lines) + "\n"

    if SECRETS_PATH.exists():
        try:
            secrets_body = SECRETS_PATH.read_text(encoding="utf-8")
        except OSError as exc:
            log.warning(
                "hal0.memory.honcho_secrets_read_failed", path=str(SECRETS_PATH), error=str(exc)
            )
        else:
            rendered += f"\n# --- operator secrets ---\n{secrets_body}"

    return rendered


def apply_honcho_env(cfg: Hal0Config, *, restart: bool = True) -> dict[str, Any]:
    """Write ``HONCHO_ENV_PATH`` for ``cfg`` and (best-effort) restart the stack.

    Returns a status dict::

        {"written", "changed", "restarted", "error"}

    ``error`` is ``None`` on full success. The write is atomic (temp + rename)
    so a crash mid-write never leaves a half-written env file that would wedge
    the compose stack. The restart only fires when the rendered content
    actually changed.
    """
    result: dict[str, Any] = {
        "written": False,
        "changed": False,
        "restarted": False,
        "error": None,
    }

    rendered = render_env(cfg)
    previous: str | None = None
    if HONCHO_ENV_PATH.exists():
        try:
            previous = HONCHO_ENV_PATH.read_text(encoding="utf-8")
        except OSError:
            previous = None

    try:
        HONCHO_ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
        tmp = HONCHO_ENV_PATH.with_suffix(".env.tmp")
        tmp.write_text(rendered, encoding="utf-8")
        tmp.replace(HONCHO_ENV_PATH)
        result["written"] = True
    except OSError as exc:
        result["error"] = f"could not write {HONCHO_ENV_PATH}: {exc}"
        log.warning("hal0.memory.honcho_env_write_failed", error=str(exc))
        return result

    result["changed"] = previous != rendered

    if not restart or not result["changed"]:
        return result

    try:
        subprocess.run(
            ["systemctl", "restart", HONCHO_SERVICE],
            check=True,
            capture_output=True,
            text=True,
            timeout=60,
        )
        result["restarted"] = True
    except (OSError, subprocess.SubprocessError) as exc:
        stderr = getattr(exc, "stderr", "") or ""
        result["error"] = (
            f"systemctl restart {HONCHO_SERVICE} failed: {exc}{(' — ' + stderr.strip()) if stderr else ''}"
        )
        log.warning("hal0.memory.honcho_restart_failed", error=str(exc))
        return result

    log.info("hal0.memory.honcho_env_applied", changed=result["changed"])
    return result


__all__ = [
    "DEFAULT_FEATURE_MODELS",
    "HONCHO_ENV_PATH",
    "HONCHO_SERVICE",
    "LOCAL_API_KEY",
    "LOCAL_BASE_URL",
    "SECRETS_PATH",
    "apply_honcho_env",
    "render_env",
]
